<?php
//dezend by http://www.yunlu99.com/
define('ROOT_PATH', '../');
require_once ROOT_PATH . 'Entry/Global.setup.php';
@set_time_limit(0);
_checkroletype('1|2|5');
$Field = $_GET['Field'];
echo '<html>' . "\r\n" . '<head>' . "\r\n" . '<meta http-equiv=content-language content=zh-cn>' . "\r\n" . '<meta http-equiv=content-type content="text/html; charset=gbk">' . "\r\n" . '<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">' . "\r\n" . '<style>' . "\r\n" . 'td { padding:2px 5px 2px 5px;}' . "\r\n" . 'table {margin-bottom:4px;}' . "\r\n" . '</style>' . "\r\n" . '<link href="../CSS/Base.css" rel=stylesheet>' . "\r\n" . '<SCRIPT type=text/javascript>' . "\r\n" . 'function Init()' . "\r\n" . '{ ' . "\r\n" . '   if( parent.document.getElementById("';
echo $Field;
echo '").value == \'\' )' . "\r\n" . '   {' . "\r\n" . '	  document.getElementById("Users").value = \'自列表中双击对象进行选择或选择对象后点击添加\';' . "\r\n" . '   }' . "\r\n" . '   else' . "\r\n" . '   {' . "\r\n" . ' 	  document.getElementById("Users").value = parent.document.getElementById("';
echo $Field;
echo '").value;' . "\r\n" . '   }' . "\r\n" . '}' . "\r\n" . '</SCRIPT>' . "\r\n" . '' . "\r\n" . '<SCRIPT>' . "\r\n" . ' function AddDataValue()' . "\r\n" . ' {' . "\r\n" . '	 var ie = document.all && !window.opera;' . "\r\n" . '	 var rows = InSet.document.getElementById("dataTable").rows;' . "\r\n" . '	 for ( var i=1; i<rows.length; i++) {' . "\r\n" . '		if( ie )' . "\r\n" . '		{' . "\r\n" . '			if( InSet.document.getElementById("dataTable").rows[i].style.backgroundColor == \'#2663e0\' )' . "\r\n" . '			{' . "\r\n" . '			   var thisValue = Trim(InSet.document.getElementById("dataTable").rows[i].cells[1].outerText);' . "\r\n" . '			   thisValue = thisValue.replace(/&nbsp;/g,\'\');' . "\r\n" . '			   AddValue(thisValue);' . "\r\n" . '			}' . "\r\n" . '		}' . "\r\n" . '		else' . "\r\n" . '		{' . "\r\n" . '            var thisColor = InSet.document.getElementById("dataTable").rows[i].style.backgroundColor;' . "\r\n" . '			if( thisColor == \'rgb(38, 99, 224)\' )' . "\r\n" . '			{' . "\r\n" . '			   var thisValue = Trim(InSet.document.getElementById("dataTable").rows[i].cells[1].outerText);' . "\r\n" . '			   thisValue = thisValue.replace(/&nbsp;/g,\'\');' . "\r\n" . '			   AddValue(thisValue);' . "\r\n" . '			}' . "\r\n" . '		}' . "\r\n" . '	 }' . "\r\n" . ' }' . "\r\n" . ' function Search()' . "\r\n" . ' {' . "\r\n" . '	 Filter = document.getElementById("SearchFor").value;' . "\r\n" . '	 if( Trim(Filter) != "" )' . "\r\n" . '	 {' . "\r\n" . '		DaURL  = "LDAPUser.php?Filter="+Filter;' . "\r\n" . '		InSet.document.location = DaURL;' . "\r\n" . '	 }' . "\r\n" . ' }' . "\r\n" . ' function SearchEvent()' . "\r\n" . ' {' . "\r\n" . '	 if(event.keyCode == 13) Search();' . "\r\n" . ' }' . "\r\n" . '' . "\r\n" . ' function RGB2HTML(red, green, blue)' . "\r\n" . ' {' . "\r\n" . '    var decColor = red + 256 * green + 65536 * blue;' . "\r\n" . '    return decColor.toString(16);' . "\r\n" . ' }' . "\r\n" . ' //去除字符串左端空格' . "\r\n" . ' function LTrim(str) {' . "\r\n" . '  return str.replace(/^\\s*/, \'\');' . "\r\n" . ' }' . "\r\n" . ' //去除字符串右端空格' . "\r\n" . ' function RTrim(str) {' . "\r\n" . '  return str.replace(/\\s*$/, \'\');' . "\r\n" . ' }' . "\r\n" . ' //去除字符串两端空格' . "\r\n" . ' function Trim(str) {' . "\r\n" . '  return LTrim(RTrim(str));' . "\r\n" . ' }' . "\r\n" . ' function Validate()' . "\r\n" . ' {' . "\r\n" . '    Values = document.getElementById("Users").value;' . "\r\n" . '    if ( Values != \'自列表中双击对象进行选择或选择对象后点击添加\' )' . "\r\n" . '	{' . "\r\n" . '       parent.document.getElementById("';
echo $Field;
echo '").value = Values;' . "\r\n" . '	}' . "\r\n" . '    parent.hidePopWin();' . "\r\n" . ' }' . "\r\n" . ' function AddValue(theValue)' . "\r\n" . ' {' . "\r\n" . '	 var currentValue = document.getElementById("Users").value;' . "\r\n" . '	 var currentArray = currentValue.split(\';\');' . "\r\n" . '	 var isHaveValue = false;' . "\r\n" . '	 for(var i=0;i<currentArray.length-1;i++)' . "\r\n" . '	 {' . "\r\n" . '		 if(Trim(currentArray[i]) == Trim(theValue) ) ' . "\r\n" . '		 {' . "\r\n" . '			 isHaveValue = true;' . "\r\n" . '			 break;' . "\r\n" . '		 }' . "\r\n" . '	 }' . "\r\n" . '	 if ( isHaveValue == false )' . "\r\n" . '	 {' . "\r\n" . '		 if ( currentValue == \'自列表中双击对象进行选择或选择对象后点击添加\' )' . "\r\n" . '		 {' . "\r\n" . '		     document.getElementById("Users").value = "";' . "\r\n" . '		 }' . "\r\n" . '		 document.getElementById("Users").value = document.getElementById("Users").value+theValue+"; ";' . "\r\n" . '	 }' . "\r\n" . ' }' . "\r\n" . '</SCRIPT>' . "\r\n" . '<META content="MSHTML 6.00.3790.0" name=GENERATOR></HEAD>' . "\r\n" . '<body oncontextmenu="return false" onload="javascript:Init();" bgcolor="#e5e5e5">' . "\r\n" . '<table style="LINE-HEIGHT: 150%;border-collapse:collapse;" cellSpacing=0 cellPadding=0 width="100%" borderColor=#cacaca border=1>' . "\r\n" . '   <div class=position>位置：&nbsp; 修改问卷属性 &raquo; 选择活动目录用户或用户组</div>' . "\r\n" . '      <tr><td bgcolor="#f9f9f9"><b>选择活动目录用户或用户组</b></td></tr>' . "\r\n" . '      <tr><td align=center height=30 valign=center>搜索(姓或名或登录名或用户组名)：<input type=text name="SearchFor" id="SearchFor" SIZE=45 onkeydown="javascript:SearchEvent();">&nbsp;<a href=\'javascript:void(0);\' onclick="javascript:Search();"><IMG SRC=\'../Images/search.gif\' width=25 height=20 BORDER=0></A></td>' . "\r\n" . '      </tr>' . "\r\n" . '	  <tr><td align=center>' . "\r\n" . '      <iframe name=\'InSet\' id=\'InSet\' src=\'\' width=100% height=175 frameBorder=1 scrolling=yes></iframe></td></tr>' . "\r\n" . '	  <tr><td><input class=inputsubmit type="Button" OnClick="AddDataValue();" VALUE="添加>>"></td></tr>' . "\r\n" . '      <tr><td align=left><textarea name=\'Users\' ID=\'Users\' COLS=116 ROWS=4></textarea></td></tr>' . "\r\n" . '	  </table>' . "\r\n" . '	  <table width=100%>' . "\r\n" . '	  <tr style="border:0px"><td style="border:0px"><input class=inputsubmit type="Button" OnClick="Validate();" VALUE="确定">&nbsp;<input class=inputsubmit type="button" name="close" value="关闭" onClick="javascript:parent.hidePopWin();"></td></tr>' . "\r\n" . '</table>' . "\r\n" . '</BODY></HTML>' . "\r\n" . '';

?>
