<?php
//dezend by http://www.yunlu99.com/
echo '<!DOCTYPE html>' . "\r\n" . '<html>' . "\r\n" . '<head>' . "\r\n" . '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />' . "\r\n" . '<title>百度地图定位GPS</title>' . "\r\n" . '<style type="text/css">' . "\r\n" . '	html{height:100%}' . "\r\n" . '	body{height:100%;margin:0px;padding:0px}' . "\r\n" . '	#container{height:100%}' . "\r\n" . '</style>' . "\r\n" . '<script type="text/javascript" src="http://api.map.baidu.com/api?v=1.4&services=false"></script>' . "\r\n" . '<script type="text/javascript" src="Convertor.js.php"></script>' . "\r\n" . '</head>' . "\r\n" . '' . "\r\n" . '<body>' . "\r\n" . '<div id="container">Loading...</div>' . "\r\n" . '<script type="text/javascript">' . "\r\n" . '' . "\r\n" . 'var gpsPoint = new BMap.Point(';
echo $_GET['gps_longitude'];
echo ', ';
echo $_GET['gps_latitude'];
echo ');  // 创建点坐标' . "\r\n" . '' . "\r\n" . '//地图初始化' . "\r\n" . 'var bm = new BMap.Map("container");' . "\r\n" . 'bm.centerAndZoom(gpsPoint, 16);' . "\r\n" . 'bm.addControl(new BMap.NavigationControl());' . "\r\n" . '' . "\r\n" . '//添加谷歌marker和label' . "\r\n" . '/*var markergps = new BMap.Marker(gpsPoint);' . "\r\n" . 'bm.addOverlay(markergps); //添加GPS标注' . "\r\n" . 'var labelgps = new BMap.Label("我是GPS标注哦",{offset:new BMap.Size(20,-10)});' . "\r\n" . 'markergps.setLabel(labelgps); //添加GPS标注*/' . "\r\n" . '' . "\r\n" . '//坐标转换完之后的回调函数' . "\r\n" . 'translateCallback = function (point){' . "\r\n" . '	var myIcon = new BMap.Icon("../Images/markers.png", new BMap.Size(23, 25), {' . "\r\n" . '		offset: new BMap.Size(10, 25),' . "\r\n" . '		imageOffset: new BMap.Size(0,0)' . "\r\n" . '	});			' . "\r\n" . '    var marker = new BMap.Marker(point, {icon: myIcon});' . "\r\n" . '    bm.addOverlay(marker);' . "\r\n" . '	marker.setAnimation(BMAP_ANIMATION_BOUNCE);' . "\r\n" . '	//var label = new BMap.Label("I\'m here",{offset:new BMap.Size(20,-10)});' . "\r\n" . '    //marker.setLabel(label); //添加百度label' . "\r\n" . '    bm.setCenter(point);' . "\r\n" . '    //alert(point.lng + "," + point.lat);' . "\r\n" . '}' . "\r\n" . '' . "\r\n" . 'setTimeout(function(){' . "\r\n" . '    BMap.Convertor.translate(gpsPoint,0,translateCallback);     //真实经纬度转成百度坐标' . "\r\n" . '}, 2000);' . "\r\n" . '</script>' . "\r\n" . '</body>' . "\r\n" . '</html>' . "\r\n" . '';

?>
