<?php
//dezend by http://www.yunlu99.com/
if (!defined('ROOT_PATH')) {
	exit('EnableQ Security Violation');
}

define('ADMINISTRATORS_TABLE', $table_prefix . 'administrators');
define('ADMINISTRATORSGROUP_TABLE', $table_prefix . 'administratorsgroup');
define('ADMINISTRATORSLOG_TABLE', $table_prefix . 'administratorslog');
define('ADMINISTRATORSLOGINLOG_TABLE', $table_prefix . 'administratorsloginlog');
define('ADMINISTRATORSCONFIG_TABLE', $table_prefix . 'administratorsconfig');
define('ADMINISTRATORSOPTION_TABLE', $table_prefix . 'administratorsoption');
define('ADMINISTRATORSOPTIONVALUE_TABLE', $table_prefix . 'administratorsoptionvalue');
define('USERGROUP_TABLE', $table_prefix . 'user_group');
define('DOWNS_TABLE', $table_prefix . 'downs');
define('BASESETTING_TABLE', $table_prefix . 'base_setting');
define('TPL_TABLE', $table_prefix . 'panel');
define('OPTION_TABLE', $table_prefix . 'option');
define('SURVEY_TABLE', $table_prefix . 'survey');
define('SURVEYCATE_TABLE', $table_prefix . 'survey_cate');
define('SURVEYCATELIST_TABLE', $table_prefix . 'survey_cate_list');
define('SURVEYPROOF_TABLE', $table_prefix . 'survey_proof');
define('PLAN_TABLE', $table_prefix . 'plan');
define('TASK_TABLE', $table_prefix . 'task_list');
define('SURVEYINDEX_TABLE', $table_prefix . 'survey_index');
define('SURVEYINDEXLIST_TABLE', $table_prefix . 'survey_index_list');
define('SURVEYINDEXRESULT_TABLE', $table_prefix . 'survey_index_result');
define('VIEWUSERLIST_TABLE', $table_prefix . 'view_user_list');
define('INPUTUSERLIST_TABLE', $table_prefix . 'input_user_list');
define('APPEALUSERLIST_TABLE', $table_prefix . 'appeal_user_list');
define('RESPONSEGROUPLIST_TABLE', $table_prefix . 'response_group_list');
define('QUESTION_TABLE', $table_prefix . 'question');
define('QUESTION_YESNO_TABLE', $table_prefix . 'question_yesno');
define('QUESTION_INFO_TABLE', $table_prefix . 'question_info');
define('QUESTION_RADIO_TABLE', $table_prefix . 'question_radio');
define('QUESTION_CHECKBOX_TABLE', $table_prefix . 'question_checkbox');
define('QUESTION_RANGE_OPTION_TABLE', $table_prefix . 'question_range_option');
define('QUESTION_RANGE_ANSWER_TABLE', $table_prefix . 'question_range_answer');
define('QUESTION_RANGE_LABEL_TABLE', $table_prefix . 'question_range_label');
define('QUESTION_RANK_TABLE', $table_prefix . 'question_rank');
define('TEXT_OPTION_TABLE', $table_prefix . 'text_option');
define('CONDITIONS_TABLE', $table_prefix . 'conditions');
define('ASSOCIATE_TABLE', $table_prefix . 'associate');
define('CONDREL_TABLE', $table_prefix . 'cond_rel');
define('CASCADE_TABLE', $table_prefix . 'cascade');
define('QUOTA_TABLE', $table_prefix . 'quota');
define('COUNTYEARNUM_TABLE', $table_prefix . 'result_year_num');
define('COUNTMONTHNUM_TABLE', $table_prefix . 'result_month_num');
define('COUNTDAYNUM_TABLE', $table_prefix . 'result_day_num');
define('COUNTGENERALINFO_TABLE', $table_prefix . 'result_general_info');
define('IPDATABASE_TABLE', $table_prefix . 'ipdatabase');
define('MAILLIST_TABLE', $table_prefix . 'mail_list');
define('REPORTDEFINE_TABLE', $table_prefix . 'report_define');
define('ARCHIVING_TABLE', $table_prefix . 'archiving');
define('REPORT_TABLE', $table_prefix . 'report');
define('COMBLIST_TABLE', $table_prefix . 'result_comb_list');
define('COMBNAME_TABLE', $table_prefix . 'result_comb_name');
define('AWARDPRODUCT_TABLE', $table_prefix . 'award_product');
define('AWARDLIST_TABLE', $table_prefix . 'award_list');
define('BANNED_TABLE', $table_prefix . 'ip_banned');
define('WHITE_TABLE', $table_prefix . 'ip_white');
define('ALLOWIP_TABLE', $table_prefix . 'ip_allow');
define('GRADE_TABLE', $table_prefix . 'grade');
define('QUERY_LIST_TABLE', $table_prefix . 'query_list');
define('QUERY_COND_TABLE', $table_prefix . 'query_cond');
define('RELATION_TABLE', $table_prefix . 'relation');
define('RELATION_LIST_TABLE', $table_prefix . 'relation_list');
define('ANDROID_LIST_TABLE', $table_prefix . 'android_list');
define('ANDROID_INFO_TABLE', $table_prefix . 'android_info');
define('ANDROID_PUSH_TABLE', $table_prefix . 'android_push');
define('ANDROID_LOG_TABLE', $table_prefix . 'android_log');
define('DATA_TRACE_TABLE', $table_prefix . 'data_trace');
define('DATA_TASK_TABLE', $table_prefix . 'data_task');
define('DEVICE_TRACE_TABLE', $table_prefix . 'device_trace');
define('GPS_TRACE_TABLE', $table_prefix . 'gps_trace');
define('GPS_TRACE_UPLOAD_TABLE', $table_prefix . 'gps_trace_upload');
define('TRACKCODE_TABLE', $table_prefix . 'track_code');
define('ISSUERULE_TABLE', $table_prefix . 'issue_rule');

?>
